name       : libgcrypt
version    : 1.8.7
release    : 24
source     :
    - https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.7.tar.bz2 : 03b70f028299561b7034b8966d7dd77ef16ed139c43440925fe8782561974748
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : GNU's basic cryptographic library
description: |
    Libgcrypt is GNU's basic cryptographic library.
emul32     : yes
optimize   :
    - size
    - lto
patterns   :
    - devel : /usr/share/aclocal
builddeps  :
    - libgpg-error-32bit-devel
setup      : |
    %configure --with-gpg-error-prefix=/usr \
               --disable-O-flag-munging \
               --enable-noexecstack
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
