name       : libgcrypt
version    : 1.8.5
release    : 21
source     :
    - https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.5.tar.bz2 : 3b4a2a94cb637eff5bdebbcaf46f4d95c4f25206f459809339cdada0eb577ac3
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
summary    : GNU's basic cryptographic library
description: |
    Libgcrypt is GNU's basic cryptographic library.
emul32     : yes
optimize   :
    - size
    - lto
patterns   :
    - devel : /usr/share/aclocal
builddeps  :
    - libgpg-error-32bit-devel
setup      : |
    %configure --with-gpg-error-prefix=/usr \
               --disable-O-flag-munging \
               --enable-noexecstack
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
