name       : libgcrypt
version    : 1.8.3
release    : 19
source     :
    - https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.3.tar.bz2 : 66ec90be036747602f2b48f98312361a9180c97c68a690a5f376fa0f67d0af7c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : system.base
emul32     : yes
optimize   :
    - size
    - lto
summary    : GNU's basic cryptographic library
description: |
    Libgcrypt is GNU's basic cryptographic library.
builddeps  :
    - libgpg-error-32bit-devel
patterns   :
    - devel : /usr/share/aclocal
setup      : |
    %apply_patches
    %configure --prefix=/usr \
               --with-gpg-error-prefix=/usr \
               --disable-O-flag-munging \
               --enable-noexecstack \
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
