name       : libgcrypt
version    : 1.7.6
release    : 11
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.7.6.tar.gz : fc0aec7714d75d812b665bd510d66031b1b2ce8fa855cc2c02238c954ea36982
license    :
    - GPL-3.0
summary    : GNU's basic cryptographic library
component  : system.base
builddeps  :
    - libgpg-error-devel
    - libgpg-error-32bit-devel
devel      : yes
emul32     : yes
patterns   :
    - devel : /usr/share/aclocal
description: |
    Libgcrypt is GNU's basic cryptographic library."
setup      : |
    %configure --with-gpg-error-prefix=/usr
build      : |
    %make
install    : |
    %make_install
