name       : libgcrypt
version    : 1.7.8
release    : 13
source     :
    - https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.7.8.tar.bz2 : 948276ea47e6ba0244f36a17b51dcdd52cfd1e664b0a1ac3bc82134fb6cec199
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : GNU's basic cryptographic library
component  : system.base
builddeps  :
    - libgpg-error-32bit-devel
devel      : yes
emul32     : yes
patterns   :
    - devel : /usr/share/aclocal
description: |
    Libgcrypt is GNU's basic cryptographic library."
setup      : |
    %configure --with-gpg-error-prefix=/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
