name        : libgcrypt
version     : 1.6.5
release     : 7
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.6.5.tar.bz2 : f49ebc5842d455ae7019def33eb5a014a0f07a2a8353dc3aa50a76fd1dafa924
license     :
    - GPL-3.0
summary     : GNU's basic cryptographic library
builddeps   :
    - libgpg-error-devel
devel       : yes
patterns    :
    - devel: /usr/share/aclocal
description : |
    Libgcrypt is GNU's basic cryptographic library."
setup      : |
    %configure --with-gpg-error-prefix=/usr
build      : |
    %make
install    : |
    %make_install
