name       : libgcrypt
version    : 1.7.7
release    : 12
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.7.7.tar.gz : 0e72e91290d553c303095a50ea660279d8f11b76c6c86e826f470442fcdf1edd
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : GNU's basic cryptographic library
component  : system.base
builddeps  :
    - libgpg-error-devel
    - libgpg-error-32bit-devel
devel      : yes
emul32     : yes
patterns   :
    - devel : /usr/share/aclocal
description: |
    Libgcrypt is GNU's basic cryptographic library."
setup      : |
    %configure --with-gpg-error-prefix=/usr
build      : |
    %make
install    : |
    %make_install
