name       : libgcrypt
version    : 1.6.6
release    : 9
source     :
    - ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.6.6.tar.gz : 21fbd6c678522ff8a62f61c9720673bf0d4a22f3b8af3b751ef2c667c49ff2bd
license    :
    - GPL-3.0
summary    : GNU's basic cryptographic library
builddeps  :
    - libgpg-error-devel
    - libgpg-error-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
devel      : yes
emul32     : yes
patterns   :
    - devel : /usr/share/aclocal
description: |
    Libgcrypt is GNU's basic cryptographic library."
setup      : |
    %configure --with-gpg-error-prefix=/usr
build      : |
    %make
install    : |
    %make_install
